# Generated by Django 5.0.1 on 2024-02-08 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jewellary', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(max_length=200, null=True)),
                ('email', models.CharField(max_length=200, null=True)),
                ('phonenumber', models.IntegerField()),
                ('username', models.CharField(max_length=200, null=True)),
                ('password', models.CharField(max_length=200, null=True)),
                ('conformpassword', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='conformpassword',
            new_name='password1',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='password',
            new_name='password2',
        ),
    ]
