# Generated by Django 5.0.1 on 2024-02-08 06:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jewellary', '0002_staff_rename_conformpassword_customer_password1_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='password1',
            new_name='password',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='password2',
        ),
    ]
