# Generated by Django 5.0.1 on 2024-02-08 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jewellary', '0003_rename_password1_customer_password_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staff',
            name='conformpassword',
        ),
    ]
