# Generated by Django 5.0.1 on 2024-02-18 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jewellary', '0005_products'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='approval',
            field=models.BooleanField(default=False),
        ),
    ]
