# Generated by Django 5.0.1 on 2024-02-20 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jewellary', '0007_alter_products_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='approval',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
